export const ActionTypes = {
  OBTENER_PELICULAS: "OBTENER_PELICULAS",
  OBTENER_GENEROS: "OBTENER_GENEROS",
  OBTENER_SESION: "OBTENER_SESION",
  OBTENER_DETALLES: "OBTENER_DETALLES",
  ENVIAR_RATING: "ENVIAR_RATING",
};
